---
version: "3.9"
networks:
  nats:
services:
  nats:
    image: nats:2.7.3-alpine3.15
    container_name: nats1
    networks:
      - nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - ./jetstream-cluster/n2:/data
    command: -js

  msir_works_producer:
    image: msir_works_producer:latest
    container_name: msir_works_producer1
    depends_on:
      - "nats"
    networks:
      - nats
    ports:
      - 9292:9292
    env_file:
      - .env

  msir_messenger:
    image: msir_messenger:latest
    container_name: msir_messenger1
    depends_on:
      - "nats"
    networks:
      - nats
    env_file:
      - .env
