---
version: "3.9"
networks:
  nats:
      
services:
  nats:
    image: nats:2.7.3-alpine3.15
    container_name: nats1
    networks:
      - nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - ./jetstream-cluster/n2:/data
    command: -js

  msir_works_producer:
    image: msir_works_producer:latest
    container_name: msir_works_producer1
    depends_on:
      - "nats"
    networks:
      - nats
    ports:
      - 9292:9292
    env_file:
      - .env

  msir_messenger:
    image: msir_messenger:latest
    container_name: msir_messenger1
    depends_on:
      - "nats"
    networks:
      - nats
    env_file:
      - .env

  otel_collector:
    image: otel/opentelemetry-collector:0.46.0-amd64
    container_name: otel_collector
    ports:
      - 4317:4317
      - 4318:4318
      - 55680:55680
        #- 55681:55681
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ${PWD}/otel-config.yaml:/etc/otel-config.yaml
        #- ./otel-config.yaml:/etc/otel-config.yaml
    env_file:
      - .env
    depends_on:
      - jaeger
      - zipkin

  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger
    ports:
      - 14250:14250
      - 16685:16685
      - 16686:16686
      - 13133:13133
        #- :55680
    env_file:
      - .env

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    env_file:
      - .env
