---
version: "3.9"
networks:
  nats:
  otel:
  loki:
      
services:
  nats:
    image: nats:2.7.3-alpine3.15
    container_name: nats1
    networks:
      - nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - ./jetstream-cluster/n2:/data
    command: -js

  msir_works_producer:
    image: msir_works_producer:latest
    container_name: msir_works_producer1
    depends_on:
      - "nats"
    networks:
      - nats
      - otel
      - loki
    ports:
      - 9292:9292
    env_file:
      - .env
    #logging:
      #driver: loki
      #options:
        #loki-url: "http://loki:3100/loki/api/v1/push"

  msir_messenger:
    image: msir_messenger:latest
    container_name: msir_messenger1
    depends_on:
      - "nats"
    networks:
      - nats
      - otel
      - loki
    env_file:
      - .env
    #logging:
      #driver: loki
      #options:
        #loki-url: "http://loki:3100/loki/api/v1/push"

  otel_collector:
    image: otel/opentelemetry-collector:0.46.0-amd64
    container_name: otel_collector
    networks:
      - otel
    ports:
      - 4317:4317
      - 4318:4318
      - 55680:55680
        #- 55681:55681
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ${PWD}/otel-config.yaml:/etc/otel-config.yaml
    env_file:
      - .env
    #depends_on:
      #- jaeger
      #- zipkin

  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger
    networks:
      - otel
    ports:
      - 14250:14250
      - 16685:16685
      - 16686:16686
      - 13133:13133
        #- :55680
    env_file:
      - .env

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - otel
    ports:
      - 9411:9411
    env_file:
      - .env

  #loki:
      #image: grafana/loki:2.4.1
      #container_name: loki
      #ports:
        #- 3100:3100
      #command: -config.file=/etc/loki/local-config.yaml
      #networks:
        #- loki

  # promtail:
  #   image: grafana/promtail:2.4.1
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml
  #   networks:
  #     - loki

  #grafana:
    #image: grafana/grafana:latest
    #networks:
      #- loki
    #ports:
      #- "3000:3000"
