receivers:
     otlp:
       protocols:
         grpc: # default gRPC port - 4317
         http: # default http port - 4318

processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s

exporters:
     jaeger:
       endpoint: jaeger:14250
       tls:
         insecure: true
     zipkin:
       endpoint: http://zipkin:9411/api/v2/spans
     logging:
       loglevel: info
       #loglevel: debug


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, zipkin, jaeger]
